"""Data supplement mode — download scripts + manual-import wait.

Based on ValidationIssue categories, generates executable download scripts
for Roboflow Universe, OpenImages, or HuggingFace datasets. In ask mode,
blocks for user confirmation; in auto mode, generates scripts and returns
False so the engine aborts cleanly (unattended runs cannot fix missing data
by re-validating in a loop).
"""

from __future__ import annotations

from pathlib import Path
from typing import Protocol

from cv_agent.data.validator import ValidationIssue
from cv_agent.tracking.run_dir import save_supplement_script
from cv_agent.ui.console import log_error, log_info, log_warning, print_validation_issues
from cv_agent.utils.logging_setup import get_logger

logger = get_logger(__name__)


class SupplementInteraction(Protocol):
    """Protocol for supplement-mode user interaction."""
    def confirm(self, message: str, default: bool = True) -> bool: ...
    def text(self, message: str, default: str = "") -> str: ...
    def press_enter(self, message: str) -> None: ...


# ---------------------------------------------------------------------------
# Script generators (regular strings, no nested triple-quotes)
# ---------------------------------------------------------------------------

def _generate_roboflow_script(class_names: list[str], output_dir: Path) -> str:
    """Generate a Python script for downloading from Roboflow Universe."""
    classes_str = ", ".join(f'"{c}"' for c in class_names)
    output = str(output_dir)

    lines = []
    lines.append('"""Roboflow Universe data supplement script.')
    lines.append(f'Generated by cv_agent — downloads datasets for: {", ".join(class_names)}')
    lines.append('"""')
    lines.append("")
    lines.append("import os")
    lines.append("from pathlib import Path")
    lines.append("")
    lines.append("# Install: pip install roboflow")
    lines.append("from roboflow import Roboflow")
    lines.append("")
    lines.append('API_KEY = os.environ.get("ROBOFLOW_API_KEY", "YOUR_API_KEY_HERE")')
    lines.append('WORKSPACE = "YOUR_WORKSPACE"')
    lines.append("")
    lines.append("rf = Roboflow(api_key=API_KEY)")
    lines.append("")
    lines.append(f"TARGET_CLASSES = [{classes_str}]")
    lines.append(f'OUTPUT_DIR = Path(r"{output}")')
    lines.append("")
    lines.append('print("Searching Roboflow Universe for relevant datasets...")')
    lines.append('print(f"Target classes: {TARGET_CLASSES}")')
    lines.append("")
    lines.append("# Example: Download a public dataset")
    lines.append('# project = rf.workspace(WORKSPACE).project("project-name")')
    lines.append('# dataset = project.version(1).download("yolov8")')
    lines.append("")
    lines.append('print("Script template generated - configure API_KEY, WORKSPACE, and project name.")')

    return "\n".join(lines)


def _generate_openimages_script(class_names: list[str], output_dir: Path) -> str:
    """Generate a shell script for downloading from OpenImages."""
    output = str(output_dir)

    lines = []
    lines.append("#!/bin/bash")
    lines.append("# OpenImages data supplement script")
    lines.append(f"# Generated by cv_agent - downloads images for: {', '.join(class_names)}")
    lines.append("#")
    lines.append("# Requires: pip install fiftyone")
    lines.append("")
    lines.append(f'OUTPUT_DIR="{output}"')
    lines.append('mkdir -p "$OUTPUT_DIR"')
    lines.append("")
    classes_python = ", ".join(repr(c) for c in class_names)
    lines.append(f'echo "Downloading OpenImages data for classes: {classes_python}"')
    lines.append("")
    lines.append("# Using FiftyOne (recommended)")
    lines.append("python -c \"")
    lines.append("import fiftyone.zoo as foz")
    lines.append("dataset = foz.load_zoo_dataset(")
    lines.append("    'open-images-v7',")
    lines.append("    split='train',")
    lines.append("    label_types=['detections'],")
    lines.append(f"    classes=[{classes_python}],")
    lines.append("    max_samples=1000,")
    lines.append("    dataset_dir='$OUTPUT_DIR',")
    lines.append(")")
    lines.append("print('Download complete.')")
    lines.append('"')
    lines.append("")
    lines.append('echo "OpenImages download script complete."')

    return "\n".join(lines)


def _generate_huggingface_script(class_names: list[str], output_dir: Path) -> str:
    """Generate a Python script for downloading from HuggingFace datasets."""
    classes_str = ", ".join(f'"{c}"' for c in class_names)
    output = str(output_dir)

    lines = []
    lines.append('"""HuggingFace datasets supplement script.')
    lines.append(f'Generated by cv_agent - searches for datasets matching: {", ".join(class_names)}')
    lines.append('"""')
    lines.append("")
    lines.append("from pathlib import Path")
    lines.append("")
    lines.append("# Install: pip install datasets huggingface_hub")
    lines.append("from huggingface_hub import HfApi")
    lines.append("")
    lines.append(f'OUTPUT_DIR = Path(r"{output}")')
    lines.append(f"TARGET_CLASSES = [{classes_str}]")
    lines.append("")
    lines.append("api = HfApi()")
    lines.append("")
    lines.append('print("Searching HuggingFace Hub for object detection datasets...")')
    lines.append('print(f"Target classes: {TARGET_CLASSES}")')
    lines.append("")
    lines.append("# List datasets matching keywords")
    lines.append("for cls in TARGET_CLASSES:")
    lines.append("    results = api.list_datasets(search=cls, task_categories=['object-detection'])")
    lines.append("    for ds in list(results)[:5]:")
    lines.append('        print(f"  - {ds.id}: {ds.description or \'no description\'}")')
    lines.append("")
    lines.append('print("\\nUse datasets.load_dataset() to download specific datasets.")')
    lines.append('print("Example: from datasets import load_dataset")')
    lines.append("print(\"  ds = load_dataset('dataset-id', split='train')\")")

    return "\n".join(lines)


def _generate_annotation_suggestion() -> str:
    """Generate annotation tool suggestions."""
    lines = []
    lines.append("# Annotation Tool Suggestions")
    lines.append("# Generated by cv_agent")
    lines.append("")
    lines.append("Recommended annotation tools for creating missing labels:")
    lines.append("")
    lines.append("1. **CVAT** (Computer Vision Annotation Tool)")
    lines.append("   - URL: https://www.cvat.ai/")
    lines.append("   - Free, open-source, web-based")
    lines.append("   - Supports YOLO export format")
    lines.append("")
    lines.append("2. **LabelImg**")
    lines.append("   - URL: https://github.com/HumanSignal/labelImg")
    lines.append("   - Lightweight desktop tool")
    lines.append("   - Direct YOLO format output")
    lines.append("")
    lines.append("3. **Roboflow Annotate**")
    lines.append("   - URL: https://roboflow.com/annotate")
    lines.append("   - Cloud-based, collaborative")
    lines.append("   - Auto-label with foundation models")
    lines.append("")
    lines.append("4. **Label Studio**")
    lines.append("   - URL: https://labelstud.io/")
    lines.append("   - Open-source, multi-format export including YOLO")

    return "\n".join(lines)


# ---------------------------------------------------------------------------
# Supplementer
# ---------------------------------------------------------------------------

class DataSupplementer:
    """Handles data deficiency resolution with script generation and user interaction."""

    def __init__(self, interaction: SupplementInteraction | None = None) -> None:
        self._interaction = interaction

    def handle(
        self,
        issues: list[ValidationIssue],
        run_dir: Path,
    ) -> bool:
        """Handle validation issues - generate scripts and/or wait for user.

        Returns:
            True if validation should be retried (e.g. the user fixed the data
            in ask mode and confirmed a retry); False if the engine should
            abort. Auto mode always returns False — an unattended run cannot
            fix missing data by re-validating in a tight loop, so we generate
            the scripts and let the engine exit cleanly instead of spinning.
        """
        print_validation_issues([i.model_dump() for i in issues])

        errors = [i for i in issues if i.severity == "error"]
        warnings = [i for i in issues if i.severity == "warning"]

        log_warning(f"Found {len(errors)} error(s) and {len(warnings)} warning(s) in dataset.")

        # Determine which classes are affected
        affected_classes: list[str] = []
        for issue in issues:
            if issue.category == "class_count":
                detail = issue.detail
                if "Class '" in detail:
                    cls_name = detail.split("'")[1]
                    if cls_name not in affected_classes:
                        affected_classes.append(cls_name)

        # Generate supplement scripts
        script_count = 0
        output_data_dir = run_dir / "supplemented_data"

        if affected_classes:
            script = _generate_roboflow_script(affected_classes, output_data_dir)
            save_supplement_script(run_dir, "roboflow_download.py", script)
            script_count += 1

            script = _generate_openimages_script(affected_classes, output_data_dir)
            save_supplement_script(run_dir, "openimages_download.sh", script)
            script_count += 1

            script = _generate_huggingface_script(affected_classes, output_data_dir)
            save_supplement_script(run_dir, "huggingface_download.py", script)
            script_count += 1

        if any(i.category in ("missing_annotations", "orphan_labels") for i in issues):
            script = _generate_annotation_suggestion()
            save_supplement_script(run_dir, "annotation_tools.md", script)
            script_count += 1

        if script_count > 0:
            log_info(f"Generated {script_count} supplement script(s) in {run_dir / 'supplement_scripts/'}")

        # Interaction: ask mode lets the user fix data and retry; auto mode
        # cannot, so abort after generating the scripts.
        from cv_agent.interaction.auto_mode import AutoModeHandler

        if self._interaction is not None and not isinstance(self._interaction, AutoModeHandler):
            try:
                retry = self._interaction.confirm_supplement([i.model_dump() for i in issues])
            except SessionQuit:
                raise
            return bool(retry)

        log_error(
            "Auto mode: dataset validation failed and cannot be auto-resolved. "
            "Run the generated supplement scripts, add the data, then re-run cv_agent."
        )
        return False