"""Data supplement mode — download scripts + manual-import wait.

Based on ValidationIssue categories, generates executable download scripts
for Roboflow Universe, OpenImages, or HuggingFace datasets. In ask mode,
blocks for user confirmation; in auto mode, prints scripts and continues.
"""

from __future__ import annotations

from pathlib import Path
from typing import Protocol

from cv_agent.data.validator import ValidationIssue
from cv_agent.tracking.run_dir import save_supplement_script
from cv_agent.ui.console import log_info, log_warning, print_validation_issues
from cv_agent.utils.logging_setup import get_logger

logger = get_logger(__name__)


# ---------------------------------------------------------------------------
# Interaction protocol (minimal stub for supplement module)
# ---------------------------------------------------------------------------

class SupplementInteraction(Protocol):
    """Protocol for supplement-mode user interaction."""
    def confirm(self, message: str, default: bool = True) -> bool: ...
    def text(self, message: str, default: str = "") -> str: ...
    def press_enter(self, message: str) -> None: ...


# ---------------------------------------------------------------------------
# Script generation
# ---------------------------------------------------------------------------

def _generate_roboflow_script(
    class_names: list[str],
    output_dir: Path,
) -> str:
    """Generate a Python script for downloading from Roboflow Universe."""
    classes_str = ", ".join(f'"{c}"' for c in class_names)
    return f'''"""Roboflow Universe data supplement script.
Generated by cv_agent — downloads datasets matching: {", ".join(class_names)}
"""

import os
from pathlib import Path

# Install: pip install roboflow
from roboflow import Roboflow

API_KEY = os.environ.get("ROBOFLOW_API_KEY", "YOUR_API_KEY_HERE")
WORKSPACE = "YOUR_WORKSPACE"

rf = Roboflow(api_key=API_KEY)

TARGET_CLASSES = [{classes_str}]
OUTPUT_DIR = Path(r"{output_dir}")

print("Searching Roboflow Universe for relevant datasets...")
print(f"Target classes: {{TARGET_CLASSES}}")

# Example: Download a public dataset
# project = rf.workspace(WORKSPACE).project("project-name")
# dataset = project.version(1).download("yolov8")

print("Script template generated — configure API_KEY, WORKSPACE, and project name.")
'''


def _generate_openimages_script(class_names: list[str], output_dir: Path) -> str:
    """Generate a shell script for downloading from OpenImages."""
    classes_arg = " ".join(class_names)
    return f'''#!/bin/bash
# OpenImages data supplement script
# Generated by cv_agent — downloads images for: {", ".join(class_names)}
#
# Requires: pip install openimages
# Or use: pip install fiftyone (for FiftyOne-based download)

OUTPUT_DIR="{output_dir}"
mkdir -p "$OUTPUT_DIR"

echo "Downloading OpenImages data for classes: {classes_arg}"

# Using FiftyOne (recommended)
python -c "
import fiftyone.zoo as foz
dataset = foz.load_zoo_dataset(
    'open-images-v7',
    split='train',
    label_types=['detections'],
    classes=[{', '.join(repr(c) for c in class_names)}],
    max_samples=1000,
    dataset_dir='$OUTPUT_DIR',
)
print('Download complete.')
"

echo "OpenImages download script complete."
'''


def _generate_huggingface_script(class_names: list[str], output_dir: Path) -> str:
    """Generate a Python script for downloading from HuggingFace datasets."""
    classes_str = ", ".join(f'"{c}"' for c in class_names)
    return f'''"""HuggingFace datasets supplement script.
Generated by cv_agent — searches for datasets matching: {", ".join(class_names)}
"""

from pathlib import Path

# Install: pip install datasets huggingface_hub
from huggingface_hub import HfApi

OUTPUT_DIR = Path(r"{output_dir}")
TARGET_CLASSES = [{classes_str}]

api = HfApi()

print("Searching HuggingFace Hub for object detection datasets...")
print(f"Target classes: {{TARGET_CLASSES}}")

# List datasets matching keywords
for cls in TARGET_CLASSES:
    results = api.list_datasets(search=cls, task_categories=["object-detection"])
    for ds in list(results)[:5]:
        print(f"  - {{ds.id}}: {{ds.description or 'no description'}}")

print("\\nUse datasets.load_dataset() to download specific datasets.")
print("Example: from datasets import load_dataset")
print("  ds = load_dataset('dataset-id', split='train')")
'''


def _generate_annotation_suggestion() -> str:
    """Generate annotation tool suggestions."""
    return """# Annotation Tool Suggestions
# Generated by cv_agent

Recommended annotation tools for creating missing labels:

1. **CVAT** (Computer Vision Annotation Tool)
   - URL: https://www.cvat.ai/
   - Free, open-source, web-based
   - Supports YOLO export format

2. **LabelImg**
   - URL: https://github.com/HumanSignal/labelImg
   - Lightweight desktop tool
   - Direct YOLO format output

3. **Roboflow Annotate**
   - URL: https://roboflow.com/annotate
   - Cloud-based, collaborative
   - Auto-label with foundation models

4. **Label Studio**
   - URL: https://labelstud.io/
   - Open-source, multi-format export including YOLO
"""


# ---------------------------------------------------------------------------
# Supplementer
# ---------------------------------------------------------------------------

class DataSupplementer:
    """Handles data deficiency resolution with script generation and user interaction."""

    def __init__(self, interaction: SupplementInteraction | None = None) -> None:
        """Initialize the supplementer.

        Args:
            interaction: Interaction handler (auto or ask mode).
        """
        self._interaction = interaction

    def handle(
        self,
        issues: list[ValidationIssue],
        run_dir: Path,
    ) -> bool:
        """Handle validation issues — generate scripts and/or wait for user.

        Args:
            issues: The validation issues to address.
            run_dir: Current experiment directory for script output.

        Returns:
            True if supplement complete and retry should happen, False to abort.
        """
        print_validation_issues([i.model_dump() for i in issues])

        errors = [i for i in issues if i.severity == "error"]
        warnings = [i for i in issues if i.severity == "warning"]

        log_warning(f"Found {len(errors)} error(s) and {len(warnings)} warning(s) in dataset.")

        # Determine which classes are affected
        affected_classes: list[str] = []
        for issue in issues:
            if issue.category == "class_count":
                # Extract class name from detail string
                detail = issue.detail
                if "Class '" in detail:
                    cls_name = detail.split("'")[1]
                    if cls_name not in affected_classes:
                        affected_classes.append(cls_name)

        # --- Generate supplement scripts ---
        script_count = 0

        if affected_classes:
            # Roboflow script
            script = _generate_roboflow_script(affected_classes, run_dir / "supplemented_data")
            save_supplement_script(run_dir, "roboflow_download.py", script)
            script_count += 1

            # OpenImages script
            script = _generate_openimages_script(affected_classes, run_dir / "supplemented_data")
            save_supplement_script(run_dir, "openimages_download.sh", script)
            script_count += 1

            # HuggingFace script
            script = _generate_huggingface_script(affected_classes, run_dir / "supplemented_data")
            save_supplement_script(run_dir, "huggingface_download.py", script)
            script_count += 1

        # Annotation suggestion if missing labels
        if any(i.category in ("missing_annotations", "orphan_labels") for i in issues):
            script = _generate_annotation_suggestion()
            save_supplement_script(run_dir, "annotation_tools.md", script)
            script_count += 1

        if script_count > 0:
            log_info(f"Generated {script_count} supplement script(s) in {run_dir / 'supplement_scripts/'}")

        # --- Interaction ---
        if self._interaction is not None:
            # Ask mode — block for user
            self._interaction.press_enter(
                "Import the missing data and press Enter to retry validation, or Ctrl+C to abort."
            )
            return True

        # Auto mode — log and continue
        log_info("Auto mode: printing supplement scripts. Re-validating on next loop iteration.")
        return True"