"""Run directory management for cv_agent experiments.

Creates timestamped experiment directories and handles artifact saving.
Directory structure for each experiment:
    runs/exp_{timestamp}/
        weights/
            best.pt
            last.pt
        args.yaml
        results.csv
        metrics.json          # custom metrics summary
        decision_log.json     # AI decision records
        data_gap_report.md    # generated by LLM on Red×3
        data_gap_report.json
        supplement_scripts/   # data supplement download scripts
"""

from __future__ import annotations

import json
import shutil
from datetime import datetime
from pathlib import Path
from typing import Any

from cv_agent.utils.logging_setup import get_logger

logger = get_logger(__name__)


def create_run_dir(output_root: Path) -> Path:
    """Create a timestamped experiment directory.

    Args:
        output_root: Root directory (e.g., Path("runs")).

    Returns:
        Path to the created run directory.
    """
    ts = datetime.now().strftime("%Y%m%d_%H%M%S")
    run_dir = output_root / f"exp_{ts}"
    (run_dir / "weights").mkdir(parents=True, exist_ok=True)
    (run_dir / "supplement_scripts").mkdir(parents=True, exist_ok=True)
    logger.info(f"Created run directory: {run_dir}")
    return run_dir


def save_artifacts(
    run_dir: Path,
    weights_source_dir: Path | None = None,
    metrics: dict[str, Any] | None = None,
    decision_log: list[dict[str, Any]] | None = None,
) -> None:
    """Save experiment artifacts to the run directory.

    Args:
        run_dir: Target run directory.
        weights_source_dir: Directory containing best.pt / last.pt (Ultralytics output).
        metrics: Dictionary of computed metrics to save as metrics.json.
        decision_log: Complete list of decision records to save to decision_log.json.
    """
    # Copy weights from Ultralytics output directory
    if weights_source_dir is not None and weights_source_dir.exists():
        for wt in ("best.pt", "last.pt"):
            src = weights_source_dir / "weights" / wt
            dst = run_dir / "weights" / wt
            if src.exists():
                shutil.copy2(src, dst)
                logger.info(f"Copied {wt} to {dst}")

    # Save metrics
    if metrics is not None:
        metrics_path = run_dir / "metrics.json"
        with open(metrics_path, "w", encoding="utf-8") as fh:
            json.dump(metrics, fh, indent=2, default=str, ensure_ascii=False)
        logger.info(f"Saved metrics to {metrics_path}")

    # Save decision log. The engine passes the full in-memory log each round, so
    # overwrite instead of appending to avoid duplicating historical entries.
    if decision_log is not None:
        log_path = run_dir / "decision_log.json"

        with open(log_path, "w", encoding="utf-8") as fh:
            json.dump(decision_log, fh, indent=2, default=str, ensure_ascii=False)
        logger.info(f"Updated decision log at {log_path}")


def snapshot_best_checkpoint(run_dir: Path, round_num: int) -> Path:
    """Copy the active best.pt to an immutable per-round snapshot.

    The active ``weights/best.pt`` is reused by later training rounds. Rollback
    needs a historical copy, not a pointer to that mutable path.
    """
    src = run_dir / "weights" / "best.pt"
    if not src.exists():
        raise FileNotFoundError(f"Best checkpoint not found: {src}")

    snapshot_dir = run_dir / "best_snapshots"
    snapshot_dir.mkdir(parents=True, exist_ok=True)
    dst = snapshot_dir / f"round_{round_num:03d}_best.pt"
    shutil.copy2(src, dst)
    logger.info(f"Snapshotted best checkpoint to {dst}")
    return dst


def save_data_gap_report(
    run_dir: Path,
    report_md: str,
    report_json: dict[str, Any],
) -> None:
    """Save the data gap report in both Markdown and JSON formats.

    Args:
        run_dir: Target run directory.
        report_md: Markdown content of the report.
        report_json: Structured JSON data of the report.
    """
    md_path = run_dir / "data_gap_report.md"
    with open(md_path, "w", encoding="utf-8") as fh:
        fh.write(report_md)
    logger.info(f"Saved data gap report (Markdown) to {md_path}")

    json_path = run_dir / "data_gap_report.json"
    with open(json_path, "w", encoding="utf-8") as fh:
        json.dump(report_json, fh, indent=2, default=str, ensure_ascii=False)
    logger.info(f"Saved data gap report (JSON) to {json_path}")


def save_supplement_script(
    run_dir: Path,
    script_name: str,
    script_content: str,
) -> Path:
    """Save a data supplement download script.

    Args:
        run_dir: Target run directory.
        script_name: Filename for the script (e.g., "roboflow_download.py").
        script_content: Content of the script file.

    Returns:
        Path to the saved script.
    """
    script_path = run_dir / "supplement_scripts" / script_name
    with open(script_path, "w", encoding="utf-8") as fh:
        fh.write(script_content)
    logger.info(f"Saved supplement script: {script_path}")
    return script_path


def load_latest_decision_log(run_dir: Path) -> list[dict[str, Any]]:
    """Load the decision log from a run directory.

    Args:
        run_dir: Path to the experiment directory.

    Returns:
        List of decision records (empty list if none found).
    """
    log_path = run_dir / "decision_log.json"
    if not log_path.exists():
        return []
    with open(log_path, encoding="utf-8") as fh:
        return json.load(fh)


def load_metrics(run_dir: Path) -> dict[str, Any] | None:
    """Load metrics.json from a run directory.

    Args:
        run_dir: Path to the experiment directory.

    Returns:
        Metrics dict or None if not found.
    """
    metrics_path = run_dir / "metrics.json"
    if not metrics_path.exists():
        return None
    with open(metrics_path, encoding="utf-8") as fh:
        return json.load(fh)


def save_session_state(run_dir: Path, state: dict[str, Any]) -> None:
    """Persist resumable session state for a training run."""
    path = run_dir / "session_state.json"
    with open(path, "w", encoding="utf-8") as fh:
        json.dump(state, fh, indent=2, default=str, ensure_ascii=False)
    logger.info(f"Saved session state to {path}")


def load_session_state(run_dir: Path) -> dict[str, Any] | None:
    """Load session_state.json if present."""
    path = run_dir / "session_state.json"
    if not path.exists():
        return None
    with open(path, encoding="utf-8") as fh:
        return json.load(fh)


def save_strategy_memory(run_dir: Path, memory: dict[str, Any]) -> None:
    """Persist strategy memory for a training run."""
    path = run_dir / "strategy_memory.json"
    with open(path, "w", encoding="utf-8") as fh:
        json.dump(memory, fh, indent=2, default=str, ensure_ascii=False)
    logger.info(f"Saved strategy memory to {path}")


def load_strategy_memory(run_dir: Path) -> dict[str, Any]:
    """Load strategy memory, returning an empty dict when none is present."""
    path = run_dir / "strategy_memory.json"
    if not path.exists():
        return {}
    with open(path, encoding="utf-8") as fh:
        return json.load(fh)


def save_strategy_log(run_dir: Path, strategy_log: list[dict[str, Any]]) -> None:
    """Persist strategy planner decisions for a training run."""
    path = run_dir / "strategy_log.json"
    with open(path, "w", encoding="utf-8") as fh:
        json.dump(strategy_log, fh, indent=2, default=str, ensure_ascii=False)
    logger.info(f"Saved strategy log to {path}")


def load_strategy_log(run_dir: Path) -> list[dict[str, Any]]:
    """Load strategy planner decisions, returning an empty list when missing."""
    path = run_dir / "strategy_log.json"
    if not path.exists():
        return []
    with open(path, encoding="utf-8") as fh:
        return json.load(fh)


def hyperparams_from_args_yaml(args_yaml: Path) -> dict[str, Any]:
    """Extract HyperParams-compatible fields from an Ultralytics args.yaml."""
    import yaml

    if not args_yaml.exists():
        return {}
    with open(args_yaml, encoding="utf-8") as fh:
        data = yaml.safe_load(fh) or {}
    from cv_agent.core.config import HyperParams

    keys = set(HyperParams.model_fields.keys())
    return {k: data[k] for k in keys if k in data}


def restore_session_state(run_dir: Path) -> dict[str, Any] | None:
    """Load session state, or reconstruct a minimal snapshot from legacy artifacts."""
    state = load_session_state(run_dir)
    if state is not None:
        return state

    decision_log = load_latest_decision_log(run_dir)
    if not decision_log:
        return None

    metrics = load_metrics(run_dir) or {}
    args_data = hyperparams_from_args_yaml(run_dir / "args.yaml")

    best_checkpoint = None
    snap_dir = run_dir / "best_snapshots"
    if snap_dir.exists():
        snaps = sorted(snap_dir.glob("round_*_best.pt"))
        if snaps:
            best_checkpoint = snaps[-1].relative_to(run_dir).as_posix()

    return {
        "round_num": len(decision_log),
        "best_score": float(metrics.get("best_score", metrics.get("score", 0.0))),
        "best_round": int(metrics.get("best_round", len(decision_log))),
        "best_checkpoint": best_checkpoint,
        "history_scores": [float(metrics.get("score", 0.0))],
        "current_params": args_data,
    }


def find_latest_run_dir(output_root: Path) -> Path | None:
    """Find the most recent experiment directory.

    Args:
        output_root: Root directory containing exp_* subdirectories.

    Returns:
        Path to the latest run directory, or None if none found.
    """
    exp_dirs = sorted(
        [d for d in output_root.iterdir() if d.is_dir() and d.name.startswith("exp_")],
        reverse=True,
    )
    return exp_dirs[0] if exp_dirs else None
